Update outdated xplat build notes
Microsoft/ChakraCore-wiki pull request #16
Opened 2016-11-07 07:02 UTC by obastemur

2016-11-07 21:45 UTC, dilijev requested changes

2016-11-07 21:45 UTC, dilijev commented on Building-ChakraCore.md
> -We will add JIT later as we progress. You can test the current support with the following instructions.
Should we continue to call out that the current implementation is still missing some features?

2016-11-07 21:45 UTC, dilijev commented on Building-ChakraCore.md
> +To build ChakraCore on Linux: (Clang 3.7+ is required)
>`To build ChakraCore on Linux: (Clang 3.7+ is required)`

`To build ChakraCore on Linux (requires Clang 3.7+):`

2016-11-07 21:45 UTC, dilijev commented on Building-ChakraCore.md
> +To build ChakraCore on OS X: (OSX 10.8+ and XCode 7.0 is installed)
>`To build ChakraCore on OS X: (OSX 10.8+ and XCode 7.0 is installed)`

`To build ChakraCore on OS X (requires OS X 10.8+ and XCode 7.0)`:

2016-11-08 03:14 UTC, obastemur commented on Building-ChakraCore.md
> -We will add JIT later as we progress. You can test the current support with the following instructions.
@dilijev  I'm not sure if this is the best place to put this.

2016-11-08 03:16 UTC, dilijev commented on Building-ChakraCore.md
> -We will add JIT later as we progress. You can test the current support with the following instructions.
Fair enough. Can you think of a better place, or do you think we shouldn't call it out in the documentation anymore since the implementation is in progress?

2016-11-08 03:33 UTC, obastemur commented on Building-ChakraCore.md
> -We will add JIT later as we progress. You can test the current support with the following instructions.
We already have it on https://github.com/Microsoft/ChakraCore/wiki/Release-Notes ?

2016-11-08 03:36 UTC, obastemur commented
@dilijev updated PR. Thanks for the review!

2016-11-08 21:33 UTC, dilijev commented on Building-ChakraCore.md
> -We will add JIT later as we progress. You can test the current support with the following instructions.
Yeah, it seems enough to track it by release that way. I think the Roadmap also indicates progress and plans. LGTM

2016-11-08 21:33 UTC, dilijev approved these changes

2016-11-08 21:34 UTC, merged

2016-11-08 21:34 UTC, dilijev commented
Approved and merged. Thanks!